framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

    # auto_mapping option is options to define which entities should be introspected by Symfony to add automatic validation constraints.
    # empty array means all entities belong to that namespace will add automatic validation
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
