# config/routes/attributes.yaml
#this configuartion tells symfony to look for routes defined as attributes on classes in the App\Controller namespace
controllers:
  resource:
    path: ../../src/Controller/
    namespace: App\Controller
  type: attribute

kernel:
  resource: App\Kernel
  type: attribute