<?php

namespace App\Controller;

use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ProductAdminController extends CRUDController
{
    public function editAction(Request $request): Response
    {
        return parent::editAction($request); // TODO: Change the autogenerated stub
    }
}
